# Generated by Django 4.2.2 on 2023-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='restos',
            name='membership',
            field=models.CharField(choices=[('1', 'Basic'), ('2', 'Standard'), ('3', 'Premium')], max_length=255, null=True),
        ),
    ]
