# Generated by Django 4.2.2 on 2023-06-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_restos_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restos',
            name='membership',
            field=models.CharField(choices=[('0', 'normal'), ('1', 'Basic'), ('2', 'Standard'), ('3', 'Premium')], default=0, max_length=255),
        ),
        migrations.DeleteModel(
            name='Memberships',
        ),
    ]
