# Generated by Django 4.2.2 on 2023-06-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_restos_membership_delete_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.bookings')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.products')),
            ],
        ),
    ]
