# Generated by Django 4.1.1 on 2023-06-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0005_product_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratings",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="bookings",
            name="product_list",
            field=models.JSONField(default=None),
        ),
        migrations.DeleteModel(
            name="product_list",
        ),
    ]
