# Generated by Django 4.1.1 on 2023-06-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0007_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="booking_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
