# Generated by Django 4.1.1 on 2023-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0008_alter_bookings_booking_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
