# Generated by Django 4.1.1 on 2023-06-19 11:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0010_remove_bookings_product_list_bookingproduct_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="product_list",
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="restos",
            name="membership",
            field=models.CharField(
                choices=[
                    ("0", "normal"),
                    ("1", "Basic"),
                    ("2", "Standard"),
                    ("3", "Premium"),
                ],
                default="0",
                max_length=255,
            ),
        ),
    ]
