# Generated by Django 4.1.1 on 2023-06-19 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0012_alter_bookings_booking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="product_list",
            field=models.ManyToManyField(
                through="club.BookingProduct", to="club.products"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
