# Generated by Django 4.1.1 on 2023-06-19 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0014_alter_bookings_booking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="booking_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
