# Generated by Django 4.1.1 on 2023-06-20 05:53

import club.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0015_alter_bookings_booking_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", club.models.CustomUserManager()),
            ],
        ),
    ]
