# Generated by Django 4.1.1 on 2023-06-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0016_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
