# Generated by Django 4.1.1 on 2023-06-20 06:46

import club.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0017_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", club.models.CustomUserManager()),
            ],
        ),
    ]
