# Generated by Django 4.1.1 on 2023-06-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0018_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restos",
            name="resto_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
