# Generated by Django 4.1.1 on 2023-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0019_alter_restos_resto_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="restos",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
