# Generated by Django 4.1.1 on 2023-06-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0021_remove_restos_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
